### ISSUE TITLE
A doubt regarding the BM-25 evaluation

### ISSUE THREAD

**Issue by anand-subu** [nianlonggu/Local-Citation-Recommendation#3]
Hi there!

I had a doubt concerning some of the source code. Specifically, I was just curious about the BM-25 implementation.

I was trying to reproduce the BM-25 scores, and had some queries:

1) Can I assume that the text of the papers here while indexing is the title + abstract?

2) Is the query to the BM-25 ranker just the local context, or the local context plus the title and abstract of the current paper the local context is from?

Sorry in advance if this might be a trivial doubt!

**Comment by nianlonggu** [comment]
Hi, 
to answer your question:
1. Yes.  Please check https://github.com/nianlonggu/Local-Citation-Recommendation/blob/8a22728494d93a9277b80cd951d94732db48e651/src/prefetch/get_inverted_index.py#L57
2. The query is the local context + title + abstract of the citing paper.  See:  https://github.com/nianlonggu/Local-Citation-Recommendation/blob/8a22728494d93a9277b80cd951d94732db48e651/src/prefetch/get_prefetched_ids.py#L108

In the branch archive-06-11-2022, there are more details about the BM25 implementation that may help to reproduce the BM25 ranking system. 
1. In the prefetch/rankers.py, there is the custom implementation of BM25: https://github.com/nianlonggu/Local-Citation-Recommendation/blob/8a22728494d93a9277b80cd951d94732db48e651/src/prefetch/rankers.py#L174
2. To use the BM25 ranker, one needs the inverted index of the database. To compute the inverted index, please refer to the script: https://github.com/nianlonggu/Local-Citation-Recommendation/blob/archive-06-11-2022/src/prefetch/get_inverted_index.py

Hope it helps.

Best,

**Comment by anand-subu** [comment]
Thanks for the detailed response! This clarified most of my doubts regarding the implementation.

I had one more question: For each of the processed datasets, am I correct in assuming the inverted index is created over the papers.json file, which comprises all the papers?

Thank you

**Comment by nianlonggu** [comment]
> 

Yes.

**Comment by anand-subu** [comment]
Thanks once again! I'm able to reproduce your scores without any issues now.

Closing this issue.
