### ISSUE TITLE
pretrained model of Reranker module

### ISSUE THREAD

**Issue by tuongtranngoc** [nianlonggu/Local-Citation-Recommendation#4]
@nianlonggu  Please check the pre-trained model of Reranker module. I didn't  load model due to miss possition_ids

Thanks

**Comment by nianlonggu** [comment]
You need to downgrade transformers version to 4.20.0 I have updated the installation description, you can reinstall the environment following: https://github.com/nianlonggu/Local-Citation-Recommendation?tab=readme-ov-file#install-dependencies
