### ISSUE TITLE
Reranking Evaluation

### ISSUE THREAD

**Issue by tuongtranngoc** [nianlonggu/Local-Citation-Recommendation#5]
@nianlonggu  How to evaluate only reranking module without running pre-fetched candidate?

**Comment by nianlonggu** [comment]
You need to downgrade transformers version to 4.20.0  I have updated the installation description, you can reinstall the environment following: https://github.com/nianlonggu/Local-Citation-Recommendation?tab=readme-ov-file#install-dependencies

**Comment by nianlonggu** [comment]
You can use the file test_with_oracle_prefetched_ids_for_reranking.json in the shared dataset on google drive. It is a list of Json string, each line contain a Json string of a data example. The "prefetched_ids" contains 2000 BM25 prefetched candidates and the actually cited id  "positive_id" is also manually added into the prefetched_ids list. With this file you do not need to run the prefetch, but just run the reranker as shown at https://github.com/nianlonggu/Local-Citation-Recommendation?tab=readme-ov-file#get-paper-recommendations

**Comment by tuongtranngoc** [comment]
Thanks @nianlonggu ,
I used the json that you mentioned, but I got error when loading it: json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 24088)
Can you help me check it?

**Comment by nianlonggu** [comment]
You can read the file line by line, and convert each line to a dictionary by json.loads()

**Comment by tuongtranngoc** [comment]
Thanks @nianlonggu, I got it
So, how to produce reranking performance as below results:
![image](https://github.com/user-attachments/assets/d86aa4e4-40dd-4d29-94cc-764ce101ee52)

I do not find guideline in README

**Comment by nianlonggu** [comment]
You can refer to the last section in https://github.com/nianlonggu/Local-Citation-Recommendation/blob/main/Turorial_Local_Citation_Recommendation.ipynb

**Comment by tuongtranngoc** [comment]
Sorry @nianlonggu , as I know, the last section is evaluated entire Recommendation Pipeline both prefetched and reranking.
I only wanna to evaluate reranker that you mentioned in paper with table 3

**Comment by nianlonggu** [comment]
Yes. But you can easily customize it by replacing the prefetched IDs with the "prefetched_ids" I mentioned in the previous Json file.

**Comment by tuongtranngoc** [comment]
thanks @nianlonggu , I got it
